### ISSUE TITLE
Clan Leader

### ISSUE THREAD

**Issue by bruno-marley** [CaptEmulation/clash-of-clans-api#8] opened 2018-04-13 23:30 UTC
How can I filter the Clan Leader?
You could have the option: clan.leader

**Comment by CaptEmulation** [comment] 2018-04-21 21:46
I am looking at https://developer.clashofclans.com/#/documentation and I don't see this option... please tell me more....

**Comment by CaptEmulation** [comment] 2018-04-23 17:15
My intention with this repo is be a simple layer over existing API.  Since there is no way to request this kind of filtering, it must be done after the request, e.g.
```
const promiseLeader = client
  .clanMembersByTag('#ABC123')
  .then(response => response.items)
  .then(clanMembers => clanMembers.find(m => m.role === 'leader'));
```
(untested)

**Comment by Choubakawa** [comment] 2018-04-23 17:40
100% agree with you !
This is what I was thinking when I said parse the memberlist.

I should have mentioned it in my message.

**Comment by bruno-marley** [comment] 2018-04-25 10:55
For me it did not work, return [object Promise]. But it was something of the sort that was asking if he had how to do it

**Comment by CaptEmulation** [comment] 2018-04-26 02:09
> For me it did not work, return [object Promise]. But it was something of the sort that was asking if he had how to do it

returning a promise is not a bug, but an intended feature.

```
const promiseLeader = client
  .clanMembersByTag('#ABC123')
  .then(response => response.items)
  .then(clanMembers => clanMembers.find(m => m.role === 'leader'))
  .then(leader => console.log(leader));
```

**Comment by CaptEmulation** [comment] 2018-04-27 14:42
All right.... I am going to close this issue as the code I posted works for me.  I am trying to keep this library simple and focus just on requests and not data transformation.

**Closed by CaptEmulation** 2018-04-27 14:42 UTC
